---
title: "1X: Introduction to R"
subtitle: "Essex Summer School for Social Science Data Analysis"
author: "Phil Swatton"
date: "09/07/2023"
output: 
    beamer_presentation:
        theme: metropolis
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



# Introduction

Welcome to 1X Intro to R!

I'm Phil, your instructor for today.

A little about me:

- Finished my PhD Government at the University of Essex this year
- Thesis on measurement of political ideology
- Day job is Data Scientist at the Alan Turing Institute

Today, we'll be learning how to use R (but you knew that already).




# Today's session

- Getting you ready to use R in the wild
- Some statistical knowledge helpful but not necessary
- Plenty of code that you can refer back to
- Some good coding practices
- Assuming no previous experience with R




# This Class

Four/five parts:

1. Using RStudio, data types, data structures
2. Importing datasets, manipulating data
3. Descriptive statistics, plots
4. Statistical tests and models
5. Functions and Loops (?)

Each section will be roughly an hour to an hour and a half long. Each section will include a set of exercises so you can practice what we've learned.

I'm not necessarily expecting you to finish the exercises today - it's okay if you don't! I will be uploading a solutions sheet to the Box folder later and as before will be available for contact throughout the second session of ESS.






# What is R? What is RStudio?

- R is:
    - Both a program and a programming language
    - Excellent for statistics & data analysis
    - Open source
- RStudio is:
    - An IDE (Integrated Development Environment)
    - Purpose-built for writing R code
    - Also open source
    - Let's take a look...





# Some useful resources

- [Google](https://www.google.com/) (no joke)
- [RStudio Learn](https://education.rstudio.com/learn/)
- [R for Data Science](https://r4ds.had.co.nz/) (for carrying on w/ Tidyverse)
- [R bloggers](https://www.r-bloggers.com/)
- [RStudio Cheatsheets](https://www.rstudio.com/resources/cheatsheets/)




# Worth doing:

- On Windows, install Rtools for R 4.2 [here](https://cran.r-project.org/bin/windows/Rtools/rtools42/rtools.html)
- On Mac, install xcode:
  - [Command line](https://clanfear.github.io/CSSS508/docs/compiling.html)
  - [App store](https://apps.apple.com/us/app/xcode/id497799835?mt=12)
- In both cases, these will help with package installation




# R package reccomendations 1

\begin{center}
\resizebox{10cm}{!}{
\begin{tabular}{lll}
\textbf{Type} 		& \textbf{Package name} 	& \textbf{Aim} \\
\hline
Data import			& \texttt{haven} 	& Similar to \texttt{foreign}, built for the \texttt{tidyverse}\\
					& \texttt{readr}	& For reading in rectangular data files (e.g. CSV), part of the \texttt{tidyverse} \\
\hline
Data cleaning 		& \texttt{tidyr} 	& Tidy datasets incl. reshaping to long and wide, part of the \texttt{tidyverse} \\
\hline
Plots 				& \texttt{ggpubr} 	& \texttt{ggplot2}-based publication-ready plots \\
					& \texttt{dotwhisker} & Easy coefficient plots in ggplot2 \\
\hline
Standard errors		& \texttt{sandwich} + \texttt{lmtest}  & Robust and clustered standard errors + test coefficients \\
\hline
Modelling			& \texttt{plm} 		& Panel data models (within-between estimator) \\
					& \texttt{zoo} or \texttt{forecast} & Time series tools \\
					& \texttt{lme4} 	& Multilevel models \\
					& \texttt{margins} or \texttt{ggeffects}& Marginal effects from models \\
					& \texttt{MASS} 	& Ordered logit models \\
					& \texttt{mlogit} or \texttt{mnlogit}	& Multinomial logit models \\
					& \texttt{AER} 		& Various (Instrumental variable, tobit models) \\ 
					& \texttt{rdd} 		& Regression discontinuity design \\
\end{tabular}
}
\end{center}



# R package reccomendations 2
\begin{center}
\resizebox{10cm}{!}{
\begin{tabular}{lll}
\textbf{Type} 		& \textbf{Package name} 	& \textbf{Aim} \\
\hline
Bayesian    & \texttt{rstan} or \texttt{rstanarm}    & Bayesian models via STAN \\
					& \texttt{rjags}   & Bayesian models via JAGS \\
					& \texttt{brms}   & Bayesian multilevel models via STAN with lme4 syntax \\
\hline
Latent Variable     & \texttt{psych}    & Exploratory Factor Analysis \\
					& \texttt{lavaan}   & CFA/SEM \\
					& \texttt{mirt}   & Item Response Theory \\
					& \texttt{mclust}   & Mixture modelling \\
\hline
Machine Learning    & \texttt{caret}    & Streamline the modelling process \\
					& \texttt{glmnet}    & lasso, ridge, elastic net regression \\
					& \texttt{rpart}, \texttt{randomforest}   & Regression trees, random forests \\
					& \texttt{e1071}   & Several misc functions including support vector machine \\
					& \texttt{neuralnet}   & Neural networks \\
					& \texttt{keras}   & R interface to Python `keras' library \\
\hline
Webscraping			& \texttt{rvest}    & Webscraping \\
					& \texttt{httr}     & Webscraping, APIs \\
					& \texttt{RSelenium} & Scraping dynamic websites \\
\hline
Text Analysis       & \texttt{quanteda}  & Quantitative text analysis \\
\end{tabular}
}
\end{center}


# Questions before we finish?







